<a href="https://colab.research.google.com/github/tanpeishing123/data_science-toolkit/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.array of size 2x2

In [2]:
import numpy as np
arr1 = np.array([[1,2],
                [3,4]])
print(arr1)

[[1 2]
 [3 4]]


2.create a random NumPy array of size 3 x 3

In [4]:
arr2 = np.random.rand(3,4)
print(arr2)

[[0.7604953  0.42920248 0.55589    0.77000621]
 [0.38683844 0.503112   0.05546232 0.03239191]
 [0.29475722 0.31873751 0.52566692 0.44735812]]


3.create a NumPy array of ones and a NumPy array of zeroes

In [7]:
ones = np.ones((2,3))
zeroes = np.zeros((2,3))
print("Array of ones:\n",ones)
print("Array of zeroes:\n",zeroes)

Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


4.Create a random NumPy array of size 6 x 3 and transpose it

In [9]:
arr3 = np.random.rand(6,3)
print("Original array:\n",arr3)
arr3T= arr3.T
print("Transposed array:\n",arr3T)

Original array:
 [[0.00763993 0.13812689 0.8221299 ]
 [0.14293432 0.81790147 0.06476007]
 [0.43701157 0.28568353 0.20595857]
 [0.18944393 0.65262066 0.92975999]
 [0.21579335 0.49115992 0.98956297]
 [0.85753797 0.93075252 0.35356513]]
Transposed array:
 [[0.00763993 0.14293432 0.43701157 0.18944393 0.21579335 0.85753797]
 [0.13812689 0.81790147 0.28568353 0.65262066 0.49115992 0.93075252]
 [0.8221299  0.06476007 0.20595857 0.92975999 0.98956297 0.35356513]]


5.Create two random arrays of size n x p and p x n then compute the dot product

In [10]:
n, p, m = 2, 3, 4
A = np.random.rand(n,p)
B = np.random.rand(p,m)

print("Matrix A:\n",A)
print("Matrix B:\n",B)

dot_product = np.dot(A,B)
print("Dot product:\n",dot_product)

Matrix A:
 [[0.76345892 0.81228071 0.33960722]
 [0.38450029 0.18991162 0.67240599]]
Matrix B:
 [[0.56005384 0.26216771 0.47289378 0.74413939]
 [0.30516599 0.12412098 0.84725965 0.54351265]
 [0.74052936 0.81138545 0.30740898 0.75417306]]
Dot product:
 [[0.92694767 0.57652772 1.15364595 1.26572732]
 [0.77123181 0.66995601 0.54943589 0.89645166]]
